ALTER TABLE tweet
ADD COLUMN id_user VARCHAR(10),
ADD COLUMN tweet_text VARCHAR(140),
ADD COLUMN create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD CONSTRAINT fk_id_user FOREIGN KEY (id_user) REFERENCES users (id_user);

SELECT* FROM tweet

DROP TABLE tweet
	

